### PR TITLE
remove dependency on specific version of Rails

### PR DESCRIPTION
**Pull request by syoder**

### CODE REVIEW

**Comment by csexton** [comment]
LGTM, wasn't sure if @cupakromer had any better suggestions on how to be compatible with Rails versions that are `4.x` and `5.x`

**Comment by cupakromer** [comment]
The greedy constraint is better than no constraint. But you can also [provide an array](http://guides.rubygems.org/patterns/#pessimistic-version-constraint) `[">= 4.0", "< 5.1"]`.

**Comment by syoder** [comment]
Oh, I didn't realize you could use an array.  What if we did `["~> 4.0", "~> 5.0"]` ?

**Comment by cupakromer** [comment]
I'm not sure how that would get parsed, but you could try. What's the goal though? If it's all version 4 and version 5 then `[">= 4.0", "< 6.0"]` would be equivalent.

**Comment by syoder** [comment]
Will this PR take the place of #17?  Feel free to close that one if that's the case.  I'm not sure why I didn't run into all the same issues you did though.  Maybe because I was using an RC and not the final release of Rails 5?

**Comment by csexton** [comment]
I didn't remember this PR. We shoulda merged it two months ago 😳 when it was opened.

I did try a fresh checkout, `bundle update`, then ran the tests. I was getting two failures.

```
  1) token authenticatable resource requests authenticatable resource will raise error if there is no token
     Failure/Error: expect{get api_index_path}.to raise_error Kracken::TokenUnauthorized
  2) token authenticatable resource requests authenticatable resource is redirected to the oauth server if there is no current user
     Failure/Error: @app.call(env)
```
<details>
<summary>RSpec Log: 60 examples, 2 failures</summary>
```
$ bundle exec rspec
DEPRECATION WARNING: `config.serve_static_files` is deprecated and will be removed in Rails 5.1.
Please use `config.public_file_server.enabled = true` instead.
 (called from block in <top (required)> at /Users/csexton/src/omniauth-radius-rails/spec/dummy/config/environments/test.rb:17)
DEPRECATION WARNING: `config.static_cache_control` is deprecated and will be removed in Rails 5.1.
Please use
`config.public_file_server.headers = { 'Cache-Control' => 'public, max-age=3600' }`
instead.
 (called from block in <top (required)> at /Users/csexton/src/omniauth-radius-rails/spec/dummy/config/environments/test.rb:18)
Run options: include {:focus=>true}

All examples were filtered out; ignoring {:focus=>true}

Randomized with seed 6872
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from <class:SessionsController> at /Users/csexton/src/omniauth-radius-rails/app/controllers/kracken/sessions_controller.rb:3)
DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from <class:SessionsController> at /Users/csexton/src/omniauth-radius-rails/app/controllers/kracken/sessions_controller.rb:4)
............FDEPRECATION WARNING: ActionDispatch::IntegrationTest HTTP request methods will accept only
the following keyword arguments in future Rails versions:
params, headers, env, xhr, as

Examples:

get '/profile',
  params: { id: 1 },
  headers: { 'X-Extra-Header' => '123' },
  env: { 'action_dispatch.custom' => 'custom' },
  xhr: true,
  as: :json
 (called from block (3 levels) in <module:Kracken> at /Users/csexton/src/omniauth-radius-rails/spec/requests/api_spec.rb:21)
F......................DEPRECATION WARNING: skip_before_filter is deprecated and will be removed in Rails 5.1. Use skip_before_action instead. (called from <class:WelcomeController> at /Users/csexton/src/omniauth-radius-rails/spec/dummy/app/controllers/welcome_controller.rb:2)
........................

Failures:

  1) token authenticatable resource requests authenticatable resource will raise error if there is no token
     Failure/Error: expect{get api_index_path}.to raise_error Kracken::TokenUnauthorized

       expected Kracken::TokenUnauthorized, got #<ArgumentError: Before process_action callback :verify_authenticity_token has not been defined> with backtrace:
         # ./lib/kracken/controllers/json_api_compatible.rb:121:in `block in included'
         # ./lib/kracken/controllers/json_api_compatible.rb:117:in `instance_exec'
         # ./lib/kracken/controllers/json_api_compatible.rb:117:in `included'
         # ./spec/dummy/app/controllers/api_controller.rb:3:in `include'
         # ./spec/dummy/app/controllers/api_controller.rb:3:in `<class:ApiController>'
         # ./spec/dummy/app/controllers/api_controller.rb:1:in `<top (required)>'
         # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:408:in `call_app!'
         # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:262:in `mock_call!'
         # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:181:in `call!'
         # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
         # ./lib/kracken/json_api/public_exceptions.rb:43:in `call'
         # ./lib/kracken/json_api/public_exceptions.rb:43:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
         # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
         # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
         # ./spec/requests/api_spec.rb:14:in `block (4 levels) in <module:Kracken>'
         # ./spec/requests/api_spec.rb:14:in `block (3 levels) in <module:Kracken>'
     # ./spec/requests/api_spec.rb:14:in `block (3 levels) in <module:Kracken>'

  2) token authenticatable resource requests authenticatable resource is redirected to the oauth server if there is no current user
     Failure/Error: @app.call(env)

     AbstractController::ActionNotFound:
       The action 'index' could not be found for ApiController
     # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:408:in `call_app!'
     # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:262:in `mock_call!'
     # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:181:in `call!'
     # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
     # ./lib/kracken/json_api/public_exceptions.rb:43:in `call'
     # ./lib/kracken/json_api/public_exceptions.rb:43:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:36:in `call_app'
     # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `block in call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/rack/logger.rb:24:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/railties-5.0.0/lib/rails/engine.rb:522:in `call'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
     # /Users/csexton/.gem/ruby/2.3.0/gems/rack-test-0.6.3/lib/rack/test.rb:124:in `request'
     # ./spec/requests/api_spec.rb:21:in `block (3 levels) in <module:Kracken>'

Finished in 0.76084 seconds (files took 1.1 seconds to load)
60 examples, 2 failures

Failed examples:

rspec ./spec/requests/api_spec.rb:13 # token authenticatable resource requests authenticatable resource will raise error if there is no token
rspec ./spec/requests/api_spec.rb:17 # token authenticatable resource requests authenticatable resource is redirected to the oauth server if there is no current user

Randomized with seed 6872
</details>

I prolly want to take the Rails dependency from the `gemspec` on this branch and merge it into #18.

**Comment by csexton** [comment]
Superseded by #18 (and by that I mean I stole @syoder's versions here and added them to the other pull request so I'd look like I knew what I am doing)

**Pull request closed without merging**
