### PR TITLE
Silence warnings when running RSpec with warnings

### PR DESCRIPTION
**Pull request by csexton**
Previously the test output began with something like this:

    kracken/rspec.rb:52: warning: method redefined; discarding old current_user
    kracken/controllers/authenticatable.rb:97: warning: previous definition of current_user was here

But some smart folks say "Don't Live with Broken Windows."

So, juggle the `$VERBOSE` setting off while redefining `current_user`.  This is a bit of a gross hack, but the idea here is to have clean pretty RSpec output when running with our Rails helpers. Hopefully encourage folks to keep the test run clean and tidy, and stave off [software
entropy][1] for a bit longer.

[1]: https://pragprog.com/the-pragmatic-programmer/extracts/software-entropy

### CODE REVIEW

**Comment by cupakromer** [comment]
I think what you want is [`undef_method`](https://ruby-doc.org/core-2.7.0/Module.html#method-i-undef_method). That's the way RSpec and Rails avoid these warnings.

However, you need to use that in the place where you redefine the method, not here in the original source. So I believe this place:

```
kracken/rspec.rb:52: warning: method redefined; discarding old current_user
```

**Comment by csexton** [comment]
TIL. Glad I added ya as a reviewer. I’ll move things around till it makes RSpec happy.

**Comment by syoder** [comment]
What’s the latest on this? I keep seeing the warning when I run the tests on Rodan.

**Comment by csexton** [comment]
I got blocked by CI on this, unless someone objects I'd like to merge this (into `rails6`) and work on CI in a different branch. Is that cool @cupakromer @syoder?

**Comment by csexton** [comment]
Got the workflow merged in and it is ✅ on all three rubies. Easier than I thought it was gonna be. 

I had to force push a few times but only @sam-kim will see my shame since he knows how to look at them old commits.

**Pull request merged**
